[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NaviOCR-vllm"
version = "0.1.0"
description = "Out-of-tree vLLM model plugin for NaviOCR-1B."
requires-python = ">=3.10"
dependencies = [
  "vllm==0.11.0",
  "transformers==4.57.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["NaviOCR_vllm*"]

[project.entry-points."vllm.general_plugins"]
NaviOCR_vllm = "NaviOCR_vllm:register" 
